# Generated by Django 5.1.1 on 2025-04-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_paymentrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
